// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonDetection.Infrastructure.Context;

#nullable disable

namespace PersonDetection.Migrations
{
    [DbContext(typeof(DetectionContext))]
    [Migration("20260211145739_updateConfig")]
    partial class updateConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonDetection.Domain.Entities.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Built-in webcam",
                            DisplayOrder = 0,
                            IsEnabled = true,
                            Name = "Webcam",
                            Type = 0,
                            Url = "0"
                        });
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.CameraSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CameraId", "IsActive");

                    b.ToTable("CameraSessions");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.DetectedPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoundingBox_Height")
                        .HasColumnType("int");

                    b.Property<int>("BoundingBox_Width")
                        .HasColumnType("int");

                    b.Property<int>("BoundingBox_X")
                        .HasColumnType("int");

                    b.Property<int>("BoundingBox_Y")
                        .HasColumnType("int");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DetectionResultId")
                        .HasColumnType("int");

                    b.Property<string>("FeatureVector")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FrameNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("GlobalPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("TimestampSeconds")
                        .HasColumnType("float");

                    b.Property<int?>("TrackId")
                        .HasColumnType("int");

                    b.Property<int?>("VideoJobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("DetectionResultId");

                    b.HasIndex("GlobalPersonId");

                    b.HasIndex("VideoJobId");

                    b.ToTable("DetectedPersons");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.DetectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalDetections")
                        .HasColumnType("int");

                    b.Property<int>("UniquePersonCount")
                        .HasColumnType("int");

                    b.Property<int>("ValidDetections")
                        .HasColumnType("int");

                    b.Property<int?>("VideoJobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("VideoJobId");

                    b.ToTable("DetectionResults");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.PersonSighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoundingBox_Height")
                        .HasColumnType("int");

                    b.Property<int>("BoundingBox_Width")
                        .HasColumnType("int");

                    b.Property<int>("BoundingBox_X")
                        .HasColumnType("int");

                    b.Property<int>("BoundingBox_Y")
                        .HasColumnType("int");

                    b.Property<int>("CameraId")
                        .HasColumnType("int");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<int?>("DetectionResultId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UniquePersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("DetectionResultId");

                    b.HasIndex("SeenAt");

                    b.HasIndex("UniquePersonId");

                    b.ToTable("PersonSightings");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.UniquePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FeatureVector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FirstSeenCameraId")
                        .HasColumnType("int");

                    b.Property<Guid>("GlobalPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastSeenCameraId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ThumbnailData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TotalSightings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlobalPersonId")
                        .IsUnique();

                    b.HasIndex("LastSeenAt");

                    b.ToTable("UniquePersons");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.VideoJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AveragePersonsPerFrame")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FrameSkip")
                        .HasColumnType("int");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PeakPersonCount")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedFrames")
                        .HasColumnType("int");

                    b.Property<double>("ProcessingTimeSeconds")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StoredFilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TotalDetections")
                        .HasColumnType("int");

                    b.Property<int>("TotalFrames")
                        .HasColumnType("int");

                    b.Property<int>("UniquePersonCount")
                        .HasColumnType("int");

                    b.Property<string>("VideoDataBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VideoDurationSeconds")
                        .HasColumnType("float");

                    b.Property<double>("VideoFps")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("State");

                    b.ToTable("VideoJobs");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.VideoPersonTimeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AverageConfidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureVector")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FirstAppearanceSeconds")
                        .HasColumnType("float");

                    b.Property<Guid>("GlobalPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LastAppearanceSeconds")
                        .HasColumnType("float");

                    b.Property<string>("ThumbnailBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAppearances")
                        .HasColumnType("int");

                    b.Property<int?>("UniquePersonId")
                        .HasColumnType("int");

                    b.Property<int>("VideoJobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlobalPersonId");

                    b.HasIndex("UniquePersonId");

                    b.HasIndex("VideoJobId");

                    b.ToTable("VideoPersonTimelines");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.DetectedPerson", b =>
                {
                    b.HasOne("PersonDetection.Domain.Entities.DetectionResult", "DetectionResult")
                        .WithMany("Detections")
                        .HasForeignKey("DetectionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonDetection.Domain.Entities.VideoJob", "VideoJob")
                        .WithMany("DetectedPersons")
                        .HasForeignKey("VideoJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DetectionResult");

                    b.Navigation("VideoJob");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.DetectionResult", b =>
                {
                    b.HasOne("PersonDetection.Domain.Entities.VideoJob", "VideoJob")
                        .WithMany("DetectionResults")
                        .HasForeignKey("VideoJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VideoJob");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.PersonSighting", b =>
                {
                    b.HasOne("PersonDetection.Domain.Entities.DetectionResult", "DetectionResult")
                        .WithMany()
                        .HasForeignKey("DetectionResultId");

                    b.HasOne("PersonDetection.Domain.Entities.UniquePerson", "UniquePerson")
                        .WithMany("Sightings")
                        .HasForeignKey("UniquePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetectionResult");

                    b.Navigation("UniquePerson");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.VideoPersonTimeline", b =>
                {
                    b.HasOne("PersonDetection.Domain.Entities.UniquePerson", "UniquePerson")
                        .WithMany()
                        .HasForeignKey("UniquePersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonDetection.Domain.Entities.VideoJob", "VideoJob")
                        .WithMany("PersonTimelines")
                        .HasForeignKey("VideoJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniquePerson");

                    b.Navigation("VideoJob");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.DetectionResult", b =>
                {
                    b.Navigation("Detections");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.UniquePerson", b =>
                {
                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("PersonDetection.Domain.Entities.VideoJob", b =>
                {
                    b.Navigation("DetectedPersons");

                    b.Navigation("DetectionResults");

                    b.Navigation("PersonTimelines");
                });
#pragma warning restore 612, 618
        }
    }
}
